function dataset = read_bom_wind(path)
%Joshua Soderholm, Feb 2016
%Climate Research Group, University of Queensland

%% WHAT
%_Reads bom HM01X (speci/30min) data generated by

%_Using the following changes to the standard configuration (ex. time)
%-extra field: station number
%-time format: YYYMMDDHH24MI
%-time interval: all
%-data: wspd (km/h) wdir (degTN)

%%

%open file and read
fid = fopen(path);
%                   hd  id name date wspd qc  wdir qc  flag  #        
C   = textscan(fid,'%*s %f %s   %s   %f   %*s %f   %*s %*f  %*s','Delimiter',',','HeaderLines',1);
 
%close file
fclose(fid);

%create struct
dataset = struct;

%fill in header
dataset.id   = C{1}(1);
dataset.name = deblank(C{2}(1));

%add time
dataset.dt   = datenum(C{3},'yyyymmddHHMM');

%add data
dataset.wspd = C{4};
dataset.wdir = C{5};

    
